/**
 * Manifest generation script for @decocms/apps.
 *
 * Scans loaders/ and actions/ directories for each app and generates
 * a typed manifest.gen.ts file with static imports and a registry map.
 *
 * Usage: npx tsx scripts/generate-manifests.ts
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep, posix } from "node:path";

const ROOT = join(import.meta.dirname!, "..");

interface AppConfig {
	name: string;
	dir: string;
}

const APPS: AppConfig[] = [
	{ name: "vtex", dir: "vtex" },
	{ name: "shopify", dir: "shopify" },
	{ name: "resend", dir: "resend" },
];

const CATEGORIES = ["loaders", "actions"] as const;
type Category = (typeof CATEGORIES)[number];

function scanDir(dir: string): string[] {
	const files: string[] = [];
	try {
		for (const entry of readdirSync(dir, { withFileTypes: true })) {
			const fullPath = join(dir, entry.name);
			if (entry.isDirectory()) {
				files.push(...scanDir(fullPath));
			} else if (
				entry.isFile() &&
				entry.name.endsWith(".ts") &&
				!entry.name.endsWith(".test.ts") &&
				!entry.name.endsWith(".spec.ts") &&
				entry.name !== "index.ts"
			) {
				files.push(fullPath);
			}
		}
	} catch {
		// Directory doesn't exist — skip
	}
	return files.sort();
}

function toImportAlias(category: Category, relPath: string): string {
	// e.g. "loaders/catalog" → "loaders_catalog"
	// e.g. "actions/cart/addItems" → "actions_cart_addItems"
	return `${category}_${relPath.replace(/\//g, "_")}`;
}

function generateManifest(app: AppConfig): string {
	const appDir = join(ROOT, app.dir);
	const imports: string[] = [];
	const entries: Record<Category, Array<{ key: string; alias: string }>> = {
		loaders: [],
		actions: [],
	};

	for (const category of CATEGORIES) {
		const categoryDir = join(appDir, category);
		const files = scanDir(categoryDir);

		for (const file of files) {
			const rel = relative(categoryDir, file)
				.replace(/\.ts$/, "")
				.split(sep)
				.join(posix.sep);

			const alias = toImportAlias(category, rel);
			const importPath = `./${category}/${rel}`;
			const manifestKey = `${app.name}/${category}/${rel}`;

			imports.push(`import * as ${alias} from "${importPath}";`);
			entries[category].push({ key: manifestKey, alias });
		}
	}

	const formatEntries = (items: Array<{ key: string; alias: string }>) =>
		items.length > 0
			? `\n${items.map(({ key, alias }) => `\t\t"${key}": ${alias},`).join("\n")}\n\t`
			: "";

	return `// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests
${imports.join("\n")}

const manifest = {
\tname: "${app.name}",
\tloaders: {${formatEntries(entries.loaders)}},
\tactions: {${formatEntries(entries.actions)}},
} as const;

export type Manifest = typeof manifest;
export default manifest;
`;
}

for (const app of APPS) {
	const content = generateManifest(app);
	const outPath = join(ROOT, app.dir, "manifest.gen.ts");
	writeFileSync(outPath, content, "utf-8");
	console.log(`Generated ${relative(ROOT, outPath)}`);
}
